# Classes

In [2]:
pes = {
    "ime": "Fido",
    "starost": 9,
    "opis": pass # funkcijo .. print(ime je star starost)
}

SyntaxError: invalid syntax (<ipython-input-2-230cdf2eaf65>, line 4)

In [3]:
class ImeRazreda:
    pass

In [5]:
class Pes:
    pass

fido = Pes()
print(fido)
print(type(fido))

<class '__main__.Pes'>


In [6]:
class Pes:
    def __init__(self):
        print("Ustvarili smo novega psa")
        
        
fido = Pes()
print(fido)
print(type(fido))

rex = Pes()
print(rex)
print(type(rex))

Ustvarili smo novega psa
<class '__main__.Pes'>
Ustvarili smo novega psa
<class '__main__.Pes'>


In [14]:
class Pes:
    def __init__(self, name, age):
        print("Ustvarili smo novega psa")
        print(self)
        self.ime = name
        self.starost = age
        
fido = Pes("Fido", 9)
print(fido)
print(fido.ime)
print(fido.starost)

rex = Pes("Rex", 12)
print(rex)
print(rex.ime)
print(rex.starost)

Ustvarili smo novega psa
Fido
9
Ustvarili smo novega psa
Rex
12


# https://bit.ly/3CZnjBj

<div class="alert alert-block alert-info">
<h1><b>Naloga: </b></h1>

Ustvarite razred Vozilo. Vsaka instanca naj ima svojo specifično hitrost in kilometrino.
    
Izpišite njegove lastnosti na sledeč način:

"Max hitrost -vozila-: -hitrost-. Prevozenih je -kilometrina- km."
</div>

Primeri:
```python
Input:
avto = Vozilo("avto", 300, 80)

Output:
Max hitrost avta: 300. Prevozenih je 80 km.

Input:
kamion = Vozilo("kamion" ,90, 33)

Output:
Max hitrost kamion: 90. Prevozenih je 33 km.

```


In [17]:
class Vozilo:
    def __init__(self, vozilo, hitrost, kilometrina):
        self.vozilo = vozilo
        self.hitrost = hitrost
        self.kilometrina = kilometrina
        
    
avto = Vozilo("avto", 300, 80)
print(f"Max hitrost {avto.vozilo}: {avto.hitrost}. Prevozenih je {avto.kilometrina} km.")

kamion = Vozilo("kamnion", 90, 33)
print(f"Max hitrost {kamion.vozilo}: {kamion.hitrost}. Prevozenih je {kamion.kilometrina} km.")

Max hitrost avto: 300. Prevozenih je 80 km.
Max hitrost kamnion: 90. Prevozenih je 33 km.


## Class methods

In [23]:
class Pes:
    def __init__(self, ime, starost):
        self.ime = ime
        self.starost = starost
        
    def opis(self):
        print(f"{self.ime} je star {self.starost} let.")
        
fido = Pes("Fido", 9)
rex = Pes("Rex", 12)

fido.opis()
rex.opis()

Fido je star 9 let.
Rex je star 12 let.


In [25]:
fido.opis()

Pes.opis(fido)

Fido je star 9 let.
Fido je star 9 let.


In [28]:
class Pes:
    def __init__(sself, ime, starost):
        sself.ime = ime
        sself.starost = starost
        
    def opis(self):
        print(f"{self.ime} je star {self.starost} let.")
        
    def vrni_starost_v_cloveskih_letih(self):
        return self.starost * 7
    
    
fido = Pes("Fido", 9)
fido.opis()
fido_human_age = fido.vrni_starost_v_cloveskih_letih()
print(fido_human_age)

rex = Pes("Rex", 12)
rex.opis()
rex_human_age = rex.vrni_starost_v_cloveskih_letih()
print(rex_human_age)

Fido je star 9 let.
63
Rex je star 12 let.
84


<div class="alert alert-block alert-info">
<h1><b>Naloga: </b></h1>
    
Ustvarite razred Vozilo. Vsaka instanca naj ima svojo specifično hitrost in kilometrino <i>in koliko goriva je bilo porabljenega do sedaj</i>.
    
<i>Razred Vozilo naj ima funkcija <b>poraba()</b>, ki vrne koliko je povprečna poraba tega vozila.</i>
</div>

Primeri:
```python
Input:
    
avto = Vozilo("avto", 300, 80, 100)
print(avto.poraba())

Output:
Vozilo porabi 6.25l/km

Input:
kamion = Vozilo("kamion", 90, 5500, 125000)
print(f"Vozilo porabi {kamion.poraba()}l/km")

Output:
Vozilo porabi 22.73l/km


```


In [32]:
class Vozilo:
    def __init__(self, vozilo, hitrost, kilometrina, gorivo):
        self.vozilo = vozilo
        self.hitrost = hitrost
        self.kilometrina = kilometrina
        self.gorivo = gorivo
        
    def poraba(self):
        return self.gorivo / self.kilometrina
    
avto = Vozilo("avto", 300, 80, 100)
print(f"Vozilo porabi {avto.poraba()} l/km")

kamion = Vozilo("kamion", 90, 5500, 125_000)
print(f"Vozilo porabi {kamion.poraba():.2f} l/km")


Vozilo porabi 1.25 l/km
Vozilo porabi 22.73 l/km


## Class variable

In [41]:
class Pes:
    hrana = ["svinjina"]
    
    def __init__(self, ime, starost):
        self.ime = ime
        self.starost = starost
        
    def opis(self):
        print(f"{self.ime} je star {self.starost} let. Najraje ima {self.hrana}")
        
        
print(Pes.hrana)

fido = Pes("Fido", 9)
rex = Pes("Rex", 12)

fido.opis()
rex.opis()

print(fido.hrana)
print(rex.hrana)

['svinjina']
Fido je star 9 let. Najraje ima ['svinjina']
Rex je star 12 let. Najraje ima ['svinjina']
['svinjina']
['svinjina']


In [43]:
class Pes:
    hrana = ["svinjina"]
    
    def __init__(self, ime, starost):
        self.ime = ime
        self.starost = starost
        
    def opis(self):
        print(f"{self.ime} je star {self.starost} let. Najraje ima {self.hrana}")
        

fido = Pes("Fido", 9)
rex = Pes("Rex", 12)

fido.opis()
rex.opis()

Pes.hrana = ["teletina"]

fido.opis()
rex.opis()

Fido je star 9 let. Najraje ima ['svinjina']
Rex je star 12 let. Najraje ima ['svinjina']
Fido je star 9 let. Najraje ima ['teletina']
Rex je star 12 let. Najraje ima ['teletina']


In [46]:
class Pes:
    hrana = ["svinjina"]
    
    def __init__(self, ime, starost):
        self.ime = ime
        self.starost = starost
        
    def opis(self):
        print(f"{self.ime} je star {self.starost}. Najraje je {self.hrana}")
        
    def dodaj_hrano(self, hrana):
        self.hrana.append(hrana)

        
fido = Pes("Fido", 9)
rex = Pes("Rex", 12)
ace = Pes("Ace", 3)

fido.opis()
rex.opis()
ace.opis()

rex.dodaj_hrano("teletina")

fido.opis()
rex.opis()
ace.opis()

Fido je star 9. Najraje je ['svinjina']
Rex je star 12. Najraje je ['svinjina']
Ace je star 3. Najraje je ['svinjina']
Fido je star 9. Najraje je ['svinjina', 'teletina']
Rex je star 12. Najraje je ['svinjina', 'teletina']
Ace je star 3. Najraje je ['svinjina', 'teletina']


In [52]:
class Pes:
    hrana = ["svinjina"]
    
    def __init__(self, ime, starost):
        self.ime = ime
        self.starost = starost
        
    def opis(self):
        print(f"{self.ime} je star {self.starost}. Najraje je {self.hrana}")
        
    def dodaj_hrano(self, nova_hrana):
        self.hrana.append(nova_hrana)
        
    def spremeni_hrano(self, nova_hrana):
        self.hrana = [nova_hrana]
        
fido = Pes("Fido", 9)
rex = Pes("Rex", 12)
ace = Pes("Ace", 3)

fido.opis()
rex.opis()
ace.opis()

rex.dodaj_hrano("teletina")
ace.spremeni_hrano("piščanec")

fido.opis()
rex.opis()
ace.opis()

Fido je star 9. Najraje je ['svinjina']
Rex je star 12. Najraje je ['svinjina']
Ace je star 3. Najraje je ['svinjina']
Fido je star 9. Najraje je ['svinjina', 'teletina']
Rex je star 12. Najraje je ['svinjina', 'teletina']
Ace je star 3. Najraje je ['piščanec']


<div class="alert alert-block alert-info">
<h1><b>Naloga: </b></h1>
    
Ustvarite razred Vozilo. Vsaka instanca naj ima svojo specifično hitrost in kilometrino in koliko goriva je bilo porabljenega do sedaj.
   
Razred Vozilo naj ima funkcija <b>poraba()</b>, ki vrne koliko je povprečna poraba tega vozila.
    
<i>Dodajte <b>class variable</b> razredu Vozilo. Spremenljivki naj bo ime <b>st_gum</b> in njena vrednost naj bo <b>4</b>.</i>
    
<i>Dodajte metodo <b>opis()</b>, ki naj izpiše opis vozila.</i>
</div>

Primeri:
```python
Input:
    
avto = Vozilo("avto", 300, 80, 500)
avto.opis()

Output:
Max hitrost avto: 300. Prevozenih je 80 km. Poraba vozila je 6.25. Vozilo ima 4 gum. 

Input:
kamion = Vozilo("kamion", 90, 5500, 125000)
kamion.opis()

Output:
Max hitrost kamion: 180. Prevozenih je 5500 km. Poraba vozila je 22.73. Vozilo ima 4 gum.


```


In [55]:
class Vozilo:
    st_gum = 4
    
    def __init__(self, vozilo, hitrost, kilometrina, gorivo):
        self.vozilo = vozilo
        self.hitrost = hitrost
        self.kilometrina = kilometrina
        self.gorivo = gorivo
        
    def poraba(self):
        return self.gorivo / self.kilometrina
    
    def opis(self):
        print(f"Max hitrost {self.vozilo}: {self.hitrost}. Prevozenih je {self.kilometrina} km. Poraba vozila je {self.poraba():.2f}. Ima {self.st_gum} gume.")
        
        
avto = Vozilo("avto", 300, 80, 500)
avto.opis()

kamion = Vozilo("kamion", 90, 5500, 125_000)
kamion.opis()

Max hitrost avto: 300. Prevozenih je 80 km. Poraba vozila je 6.25. Ima 4 gume.
Max hitrost kamion: 90. Prevozenih je 5500 km. Poraba vozila je 22.73. Ima 4 gume.


# Decorators

In [60]:
class Pes:
    vrsta = "Pes"
    hrana = ["svinjina"]
    
    def __init__(self, ime, starost):
        self.ime = ime
        self.starost = starost
    
    def opis(self):
        return f"{self.ime} je star {self.starost}. Najraje je {self.hrana}. Je vrste {self.vrsta}"
    
    @classmethod
    def spremeni_vrsto(csl, vrsta):
        print(csl)
        csl.vrsta = vrsta
        
fido = Pes("Fido", 9)
rex = Pes("Rex", 12)

print(fido.opis())
print(rex.opis())

fido.spremeni_vrsto("kuščar")

print(fido.opis())
print(rex.opis())

Fido je star 9. Najraje je ['svinjina']. Je vrste Pes
Rex je star 12. Najraje je ['svinjina']. Je vrste Pes
<class '__main__.Pes'>
Fido je star 9. Najraje je ['svinjina']. Je vrste kuščar
Rex je star 12. Najraje je ['svinjina']. Je vrste kuščar


In [63]:
class Pes:
    vrsta = "Pes"
    hrana = ["svinjina"]
    
    def __init__(self, ime, starost):
        self.ime = ime
        self.starost = starost
        
    def opis(self):
        return f"{self.ime} je star {self.starost}. Najraje je {self.hrana}. Je vrste {self.vrsta}"
    
    @staticmethod
    def dolzina_ime(ime):
        return len(ime)
    
fido = Pes("Fido", 9)
rex = Pes("Rex", 12)

print(fido.opis())
print(rex.opis())

print(fido.dolzina_ime(fido.ime))

Fido je star 9. Najraje je ['svinjina']. Je vrste Pes
Rex je star 12. Najraje je ['svinjina']. Je vrste Pes
4


# Class inheritance

In [65]:
class Pes:
    vrsta = "Pes"
    hrana = ["svinjina"]
    
    def __init__(self, ime, starost):
        self.ime = ime
        self.starost = starost
        
    def opis(self):
        print(f"{self.ime} je star {self.starost}. Najraje je {self.hrana} in je vrste {self.vrsta}")
        
fido = Pes("Fido", 9)
fido.opis()

Fido je star 9. Najraje je ['svinjina'] in je vrste Pes


In [66]:
class Bulldog(Pes):
    pass

spencer = Bulldog("Spencer", 15)
print(type(spencer))
print(spencer)
spencer.opis()

<class '__main__.Bulldog'>
Spencer je star 15. Najraje je ['svinjina'] in je vrste Pes


In [70]:
class Pes:
    vrsta = "Pes"
    hrana = ["svinjina"]
    
    def __init__(self, ime, starost):
        self.ime = ime
        self.starost = starost
        
    def opis(self):
        print(f"{self.ime} je star {self.starost}. Najraje je {self.hrana} in je vrste {self.vrsta}")
        

class Bulldog(Pes):
    def bark(self):
        print("Woof woof")

spencer = Bulldog("Spencer", 15)
fido = Pes("Fido", 9)

spencer.opis()
fido.opis()

spencer.bark()
fido.bark()

Spencer je star 15. Najraje je ['svinjina'] in je vrste Pes
Fido je star 9. Najraje je ['svinjina'] in je vrste Pes
Woof woof


AttributeError: 'Pes' object has no attribute 'bark'

In [71]:
class Pes:
    vrsta = "Pes"
    hrana = ["svinjina"]
    
    def __init__(self, ime, starost):
        self.ime = ime
        self.starost = starost
        
    def opis(self):
        print(f"{self.ime} je star {self.starost}. Najraje je {self.hrana} in je vrste {self.vrsta}")
        

class Bulldog(Pes):
    vrsta = "Bulldog"
    
    def bark(self):
        print("Woof woof")
        
fido = Pes("Fido", 9)
spencer = Bulldog("Spencer", 12)

fido.opis()
spencer.opis()

Fido je star 9. Najraje je ['svinjina'] in je vrste Pes
Spencer je star 12. Najraje je ['svinjina'] in je vrste Bulldog


In [74]:
class Pes:
    vrsta = "Pes"
    hrana = ["svinjina"]
    
    def __init__(self, ime, starost):
        self.ime = ime
        self.starost = starost
        
    def opis(self):
        print(f"{self.ime} je star {self.starost}. Je {self.hrana} in je vrste {self.vrsta}")


class Bulldog(Pes):
    vrsta = "Bulldog"
    def __init__(self, ime, starost, najljubsa_hrana):
        #self.ime = ime
        #self.starost = starost
        super().__init__(ime, starost)
        self.najljubsa_hrana = najljubsa_hrana
        
    def opis(self):
        print(f"{self.ime} je star {self.starost}. Je {self.hrana} ampak najraje {self.najljubsa_hrana} in je vrste {self.vrsta}")


fido = Pes("Fido", 9)
spencer = Bulldog("Spencer", 12, "čevapi")

fido.opis()
spencer.opis()

Fido je star 9. Je ['svinjina'] in je vrste Pes
Spencer je star 12. Je ['svinjina'] ampak najraje čevapi in je vrste Bulldog


<div class="alert alert-block alert-info">
<h1><b>Naloga: </b></h1>
    
Ustvarite razred Vozilo. Vsaka instanca naj ima svojo specifično hitrost in kilometrino in koliko goriva je bilo porabljenega do sedaj.
   
Razred Vozilo naj ima funkcija <b>poraba()</b>, ki vrne koliko je povprečna poraba tega vozila.
    
Dodajte <b>class variable</b> razredu Vozilo. Spremenljivki naj bo ime <b>st_gum</b> in njena vrednost naj bo <b>4</b>.
Dodajte metodo <b>opis()</b>, ki naj izpiše opis vozila.
    
    
<i>Ustvarite podrazreda <b>Avto</b> in <b>Motor</b>. Razreda naj dedujete od razreda Vozila. Motor razred naj prepiše spremenljivko <b>st_gum</b> v <b>2</b>. Vsak razred naj pravilno shrani ime vozila, ko ustvarimo novo instanco.</i></div>

Primeri:
```python
Input:
avto = Avto(300, 80, 500)
avto.opis()
Output:
Max hitrost avto: 300. Prevozenih je 80 km. Poraba vozila je 6.25 l/km. Vozilo ima 4 gum.
Input:
motor = Motor(90, 220, 520)
motor.opis()
Output:
Max hitrost motor: 90. Prevozenih je 220 km. Poraba vozila je 2.36 l/km. Vozilo ima 2 gum.
```


In [83]:
class Vozilo:
    st_gum = 4
    
    def __init__(self, vozilo, hitrost, kilometrina, gorivo):
        self.vozilo = vozilo
        self.hitrost = hitrost
        self.kilometrina = kilometrina
        self.gorivo = gorivo
        
    def poraba(self):
        return self.gorivo/self.kilometrina
    
    def opis(self):
        print(f"Max hitrost {self.vozilo}: {self.hitrost}. Prevozenih je {self.kilometrina} km. Poraba je {self.poraba():.2f} l/km. Vozilo ima {self.st_gum} gum.")
        
        
class Avto(Vozilo):
    def __init__(self, hitrost, kilometrina, gorivo):
        super().__init__("avto", hitrost, kilometrina, gorivo)
        
class Motor(Vozilo):
    st_gum = 2
    
    def __init__(self, hitrost, kilometrina, gorivo):
        super().__init__("motor", hitrost, kilometrina, gorivo)

#avto = Vozilo("avto", 300, 80, 500)
avto = Avto(300, 80, 500)
avto.opis()

#motor = Vozilo("motor", 90, 220, 520)
motor = Motor(90, 220, 520)
motor.opis()

Max hitrost avto: 300. Prevozenih je 80 km. Poraba je 6.25 l/km. Vozilo ima 4 gum.
Max hitrost motor: 90. Prevozenih je 220 km. Poraba je 2.36 l/km. Vozilo ima 2 gum.


# Multiple inheritance

In [89]:
class SuperA:
    varA = 10
    def funa(self):
        return 11
    
class SuperB:
    varB = 20
    def funb(self):
        return 21
    
class Sub(SuperA, SuperB):
    pass

obj_ = Sub()

print(obj_.varA)
print(obj_.funa())
print(obj_.varB)
print(obj_.funb())

10
11
20
21


In [94]:
class A:
    varA = 100
    def fun(self):
        print("a")
        
class B:
    varB = 200
    def fun(self):
        print("b")
        
class C(A, B):
    pass

obj_ = C()
print(obj_.varA)
print(obj_.varB)
obj_.fun()

100
200
a


In [95]:
class Level0:
    var = 0
    def fun(self):
        return 0
    
class Level1(Level0):
    var = 100
    def fun(self):
        return 101
    
class Level2(Level1):
    pass

obj_ = Level2()
print(obj_.var)
print(obj_.fun())

100
101


In [101]:
class Level0:
    var = 0
    def fun(self):
        return 0
    
class Level1(Level0):
    var = 1
    def fun(self):
        return 101
    
class Level2(Level1):
    pass


l0 = Level0()
l1 = Level1()
l2 = Level2()

print(isinstance(l2, Level2))
print(isinstance(l2, Level1))
print(isinstance(l2, Level0))
print("-------")
print(isinstance(l1, Level0))
print(isinstance(l1, Level1))
print(isinstance(l1, Level2))

True
True
True
-------
True
True
False


In [102]:
import inspect

class Level0:
    var = 0
    def fun(self):
        return 0
    
class Level1(Level0):
    var = 100
    def fun(self):
        return 101
    
class Level2(Level1):
    pass


inspect.getmro(Level2)

(__main__.Level2, __main__.Level1, __main__.Level0, object)

## Banka

Napišite program:

```python
class Oseba():
    def __init__(self, ime, priimek):
        # za to instanco naj ustvari spremenljivki ime in priimek
    def __str__(self):
        # vrne naj string, znotraj katerega imamo ime in priimek
        
        
class Stranka(): # class naj deduje od razreda Oseba()
    def nastavi_stanje(self, stanje):
        # metoda naj ustvari spremenljivko samo za to instaco razreda. Vrednost naj bo "stanje" oziroma default vrednost naj bo 0. Metoda naj nato vrne vrednost spremenljivke stanje
    def dvig(self, znesek):
        # Od stanja naj se odšteje znesek.
        # V kolikor ni dovolj denarja na računu naj se dvigne z banke celotno stanje
        # Na koncu naj metoda vrne dvignjen znesek
    def polog(self, znesek):
        # metoda naj doda velikost zneska stanju
        # nato naj metoda vrne novo stanje
        
INPUT:
objekt = Stranka("Gregor", "Balkovec")
print(objekt)
print(objekt.nastavi_stanje())
print(objekt.polog(5000))
print(objekt.dvig(2000))
print(objekt.dvig(4000))

OUTPUT:
Gregor Balkovec
0.0
5000.0
2000
Dal ti bom samo 3000.0
3000.0

```

In [106]:
class Oseba():
    def __init__(self, ime, priimek):
        # za to instanco naj ustvari spremenljivki ime in priimek
        self.ime = ime
        self.priimek = priimek
        
    def __str__(self):
        # vrne naj string, znotraj katerega imamo ime in priimek
        return f"{self.ime} {self.priimek}"

class Stranka(Oseba): # class naj deduje od razreda Oseba()
    def nastavi_stanje(self, stanje=0):
        # metoda naj ustvari spremenljivko samo za to instaco razreda. Vrednost naj bo "stanje" oziroma default vrednost naj bo 0. Metoda naj nato vrne vrednost spremenljivke stanje
        self.stanje = stanje
        return self.stanje
        
    def dvig(self, znesek):
        # Od stanja naj se odšteje znesek.
        # V kolikor ni dovolj denarja na računu naj se dvigne z banke celotno stanje
        # Na koncu naj metoda vrne dvignjen znesek
        dvign = 0
        if znesek > self.stanje:
            print("Dal ti bom samo", self.stanje)
            dvig = self.stanje
            self.stanje = 0
        else:
            self.stanje -= znesek
            dvig = znesek
        return dvig
    
    def polog(self, znesek):
        # metoda naj doda velikost zneska stanju
        # nato naj metoda vrne novo stanje
        self.stanje += znesek
        return self.stanje
        
objekt = Stranka("Gregor", "Balkovec")
print(objekt)
print(objekt.nastavi_stanje())
print(objekt.polog(5000))
print(objekt.dvig(2000))
print(objekt.dvig(4000))

Gregor Balkovec
0
5000
2000
Dal ti bom samo 3000
3000


# Class - Pismo in Posta

```python

    
class Posta:    
    def __init__(self, stevilka, naziv):
        # Vsaka instanca razreda Posta naj vsebuje: 
        # - :string: naziv poste (Primer: Ljubljana) 
        # - :integer: stevilka poste (Primer: 1000)
        pass
    def vrni_stevilko(self, ...):
        # vrne naj :integer: stevilko
        pass
    def vrni_naziv(self):
        # vrne naj :string: naziv poste
        pass
    def to_string(self):
        # vrne naj string v sledeči obliki: stevilka naziv (Primer: 1000 Ljubljana)
        pass
    
class Pismo:
    def __init__(self, izvorna_posta, ciljna_posta, vrsta_pisma):
        # Vsaka instanca razreda naj vsebuje:
        # - :posta: izvorna_posta (Primer: 1000 Ljubljana)
        # - :posta: ciljna_posta (Primer: 2000 Maribor)
        # - :string: vrsta_pisma (priporočeno ali navadno)
        pass
    def to_string(self, ...):
        # vrne naj :string: ki opisuje pismo (Primer: 1000 Ljubljana -> 2000 Maribor [P])
            # [P] če je pismo priporočeno, [N] če je pismo navadno
        pass
    def sta_izvor_in_cilj_ista(self, ...):
        # Vrne True če sta stevilke izvorne in ciljne poste isti
        pass
        
TESTIRANJE:
posta_ljubljana = Posta(1000, "Ljubljana")
posta_maribor = Posta(2000, "Maribor")
pismo1 = Pismo(posta_ljubljana, posta_maribor, "priporočeno")
pismo2 = Pismo(posta_maribor, posta_maribor, "navadno")
print(pismo1.to_string())
print(pismo2.to_string())
print(pismo2.sta_izvor_in_cilj_ista())

VRNE NAJ:
1000 Ljubljana -> 2000 Maribor [P]
2000 Maribor -> 2000 Maribor [N]
True
```

In [124]:
class Posta:    
    def __init__(self, stevilka, naziv):
        # Vsaka instanca razreda Posta naj vsebuje: 
        # - :string: naziv poste (Primer: Ljubljana) 
        # - :integer: stevilka poste (Primer: 1000)
        self.stevilka = stevilka
        self.naziv = naziv

    def vrni_stevilko(self):
        # vrne naj :integer: stevilko
        return self.stevilka
    
    def vrni_naziv(self):
        # vrne naj :string: naziv poste
        return self.naziv
    
    def to_string(self):
        # vrne naj string v sledeči obliki: stevilka naziv (Primer: 1000 Ljubljana)
        return f"{self.stevilka} {self.naziv}"

class Pismo:
    def __init__(self, izvorna_posta, ciljna_posta, vrsta_pisma):
        # Vsaka instanca razreda naj vsebuje:
        # - :posta: izvorna_posta (Primer: 1000 Ljubljana)
        # - :posta: ciljna_posta (Primer: 2000 Maribor)
        # - :string: vrsta_pisma (priporočeno ali navadno)
        self.izvorna_posta = izvorna_posta
        self.ciljna_posta = ciljna_posta
        self.vrsta_pisma = vrsta_pisma
        
    def to_string(self):
        # vrne naj :string: ki opisuje pismo (Primer: 1000 Ljubljana -> 2000 Maribor [P])
            # [P] če je pismo priporočeno, [N] če je pismo navadno
        string = f"{self.izvorna_posta.to_string()} -> {self.ciljna_posta.to_string()}"
        if self.vrsta_pisma == "priporočeno":
            string += " [P]"
        else:
            string += " [N]"
        return string
    def sta_izvor_in_cilj_ista(self):
        # Vrne True če sta stevilke izvorne in ciljne poste isti
        if self.izvorna_posta.stevilka == self.ciljna_posta.stevilka:
            return True
        else:
            return False

    
posta_ljubljana = Posta(1000, "Ljubljana")
posta_maribor = Posta(2000, "Maribor")
print(posta_ljubljana.to_string())
pismo1 = Pismo(posta_ljubljana, posta_maribor, "priporočeno")
pismo2 = Pismo(posta_maribor, posta_maribor, "navadno")
print(pismo1.to_string())
print(pismo2.to_string())
print(pismo2.sta_izvor_in_cilj_ista())

1000 Ljubljana
1000 Ljubljana -> 2000 Maribor [P]
2000 Maribor -> 2000 Maribor [N]
True
